spring:
  datasource:
    username: root
    password: 20151349
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.mateEase.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml